name: lost_and_tossed
description: A playful community field guide for documenting found, discarded, or posted public objects.
version: 0.2.4+8142022

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI Icons
  cupertino_icons: ^1.0.6
  
  # State Management
  flutter_riverpod: ^2.4.5
  riverpod_annotation: ^2.2.1
  
  # Navigation
  go_router: ^12.1.1
  
  # Internationalization
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
    
  # Supabase
  supabase_flutter: ^2.3.4
  
  # Authentication
  google_sign_in: ^6.2.1
  
  # Location & Maps
  geolocator: ^10.1.0
  latlong2: ^0.8.1
  dart_geohash: ^2.1.0
  
  # Image handling & ML
  image_picker: ^1.0.4
  image: ^4.1.3
  google_mlkit_face_detection: ^0.10.0
  google_mlkit_text_recognition: ^0.13.0
  
  # UI Components
  cached_network_image: ^3.3.0
  photo_view: ^0.14.0
  flutter_staggered_grid_view: ^0.7.0
  
  # Utilities
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  share_plus: ^7.2.1
  uuid: ^4.1.0
  
  # Logging & Analytics
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  riverpod_generator: ^2.3.5
  build_runner: ^2.4.7
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  
  # Linting
  flutter_lints: ^3.0.0
  
  # Testing
  mocktail: ^1.0.1
  golden_toolkit: ^0.15.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/images/
    
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
        - asset: assets/fonts/Inter-Italic-VariableFont_opsz,wght.ttf
          style: italic
