name: Basic CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test & Analyze
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.8'  # Match local development version
        cache: true
    
    - name: Install dependencies
      run: flutter pub get
    
    # Removed formatting check - uncomment if you want strict formatting
    # - name: Verify formatting
    #   run: dart format --output=none --set-exit-if-changed .
    
    - name: Analyze project source
      run: flutter analyze --no-fatal-infos
    
    - name: Run unit tests
      run: flutter test

  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.8'
        cache: true
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
    
    - name: Install dependencies
      run: flutter pub get
    
    # Explicitly clean and verify AndroidX settings before build
    - name: Clean build artifacts
      run: |
        flutter clean
        cd android && ./gradlew clean && cd ..
    
    - name: Verify AndroidX configuration
      run: |
        echo "Checking gradle.properties for AndroidX settings..."
        grep -n "android.useAndroidX" android/gradle.properties || echo "AndroidX property not found!"
        grep -n "android.enableJetifier" android/gradle.properties || echo "Jetifier property not found!"
    
    - name: Build APK (Development version)
      run: flutter build apk --debug --target=lib/main_dev.dart
    
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: debug-apk
        path: build/app/outputs/flutter-apk/app-debug.apk
