name: Basic CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test & Analyze
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.8'  # Match local development version
        cache: true
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Analyze project source
      run: flutter analyze --no-fatal-infos
    
    - name: Run unit tests
      run: flutter test

  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.8'
        cache: true
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Debug AndroidX configuration
      run: |
        echo "=== Checking gradle.properties content ==="
        cat android/gradle.properties
        echo ""
        echo "=== Checking build.gradle content ==="
        tail -10 android/app/build.gradle
        echo ""
        echo "=== Checking if gradle.properties exists in expected location ==="
        ls -la android/gradle.properties
    
    - name: Build APK (Development version)
      run: flutter build apk --debug --target=lib/main_dev.dart
    
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: debug-apk
        path: build/app/outputs/flutter-apk/app-debug.apk
